### ISSUE TITLE
Joining a group by invite code doesn't work

### ISSUE THREAD

**Issue by shmezi** [Auties00/Whatsapp4j#144]
java.util.concurrent.TimeoutException: Node[description=iq, attributes={xmlns=w:g2, to=g.us, id=a6-11, type=set}, content=[Node[description=invite, attributes={invite=INVITE_CODE}]]] timed out: no response from WhatsApp
	at it.auties.whatsapp.model.request.Request.cancelTimedFuture(Request.java:51)
	at it.auties.whatsapp.model.request.Request.lambda$with$0(Request.java:42)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Auties00** [comment]
> java.util.concurrent.TimeoutException: Node[description=iq, attributes={xmlns=w:g2, to=g.us, id=a6-11, type=set}, content=[Node[description=invite, attributes={invite=INVITE_CODE}]]] timed out: no response from WhatsApp at it.auties.whatsapp.model.request.Request.cancelTimedFuture(Request.java:51) at it.auties.whatsapp.model.request.Request.lambda$with$0(Request.java:42) at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Should be fixed in 3.0-RC12, let me know

**Comment by shmezi** [comment]
So not sure if I'm doing something wrong but literally nothing happens, sometimes it freezes the bot sometimes it doesn't..  I've tried using the full link and just the code neither have worked

**Comment by shmezi** [comment]
@Auties00 forgot to ping you in previous message

**Comment by Auties00** [comment]
> So not sure if I'm doing something wrong but literally nothing happens, sometimes it freezes the bot sometimes it doesn't.. I've tried using the full link and just the code neither have worked

check the latest version, I'm working on a fix. it shouldn't be ready but maybe it works

**Comment by Auties00** [comment]
Still no fix for this issue sadly, I'm working on it though

**Comment by shmezi** [comment]
Still no luck on a solution?

**Comment by shmezi** [comment]
@Auties00 still no luck?

**Comment by shmezi** [comment]
@Auties00 any news or is it just weird?

**Comment by Auties00** [comment]
> @Auties00 any news or is it just weird?

I've found no fix. Is this something you need urgently? I can prioritize it if that's the case

**Comment by shmezi** [comment]
> > @Auties00 any news or is it just weird?
> 
> I've found no fix. Is this something you need urgently? I can prioritize it if that's the case

Not urgently, no.. Waiting on it for full release of my bot, but really it's completely fine.. just was wondering if there was an update on it.

**Comment by Auties00** [comment]
> > > @Auties00 any news or is it just weird?
> > 
> > 
> > I've found no fix. Is this something you need urgently? I can prioritize it if that's the case
> 
> Not urgently, no.. Waiting on it for full release of my bot, but really it's completely fine.. just was wondering if there was an update on it.

Fixed in RC21, please lmk

**Comment by shmezi** [comment]
> > > > @Auties00 any news or is it just weird?
> > > 
> > > 
> > > I've found no fix. Is this something you need urgently? I can prioritize it if that's the case
> > 
> > 
> > Not urgently, no.. Waiting on it for full release of my bot, but really it's completely fine.. just was wondering if there was an update on it.
> 
> Fixed in RC21, please lmk

Cool thanks! I found a weird bug that will make the application on certain pcs just not work after reboot, Ill try to find a real cause tho

**Comment by Auties00** [comment]
> > > > > @Auties00 any news or is it just weird?
> > > > 
> > > > 
> > > > I've found no fix. Is this something you need urgently? I can prioritize it if that's the case
> > > 
> > > 
> > > Not urgently, no.. Waiting on it for full release of my bot, but really it's completely fine.. just was wondering if there was an update on it.
> > 
> > 
> > Fixed in RC21, please lmk
> 
> Cool thanks! I found a weird bug that will make the application on certain pcs just not work after reboot, Ill try to find a real cause tho

Can you confirm though that this issue is fixed? so at least we can close this hahaha

**Comment by shmezi** [comment]
@Auties00 sorry m8 to tell you this.. but unless im doing something wrong its still broken..

```kt
        api.acceptGroupInvite("code")
``` thats what I was testing, code Ive tried both the link itself and the code itself

**Comment by Auties00** [comment]
> @Auties00 sorry m8 to tell you this.. but unless im doing something wrong its still broken..
> 
> ```kotlin
>         api.acceptGroupInvite("code")
> ```
> 
> thats what I was testing, code Ive tried both the link itself and the code itself

Can you try with RC26? also try to query the code instead of hard coding it, maybe it's expired

**Comment by shmezi** [comment]
> > @Auties00 sorry m8 to tell you this.. but unless im doing something wrong its still broken..
> > ```kotlin
> >         api.acceptGroupInvite("code")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > thats what I was testing, code Ive tried both the link itself and the code itself
> 
> Can you try with RC26? also try to query the code instead of hard coding it, maybe it's expired

Its for sure not an old link since I just generated the link

**Comment by shmezi** [comment]
Also @Auties00 Querying isnt what I want.. Since I just want to join a group via a code that they arent in already...

**Comment by shmezi** [comment]
Just tested it, for some groups it works for some it doesnt.. Ive tried remaking  the link a few times

**Comment by Auties00** [comment]
> Just tested it, for some groups it works for some it doesnt.. Ive tried remaking the link a few times

Uhm is there any clear difference between which groups work and which Don't?

**Comment by shmezi** [comment]
No clue one is a big group with 200ish ppl, which for some reason other things don't work in it.. and mine is a small group

**Comment by Auties00** [comment]
> No clue one is a big group with 200ish ppl, which for some reason other things don't work in it.. and mine is a small group

What doesn't work? Btw I'll try to use the analyzer to fix it, maybe there are different requests based on the group size and type

**Comment by shmezi** [comment]
Yes, I'll send the error on telegram just because it includes info that I don't feel like removing.

**Comment by shmezi** [comment]
@Auties00 any news on this by chance?
Thanks

**Comment by Auties00** [comment]
> @Auties00 any news on this by chance? Thanks

It should work as of now, Whatsapp uses the same exact node. You can try to test it again

**Comment by shmezi** [comment]
Hmm doesn't seem to work, it doesn't throw an exception either.. mind sending a snip it of code to make sure I'm using it correctly? It was also unclear if I'm supposed to use the actual code or the link ( should specify it)
Thanks, shmezi

**Comment by Auties00** [comment]
> Hmm doesn't seem to work, it doesn't throw an exception either.. mind sending a snip it of code to make sure I'm using it correctly? It was also unclear if I'm supposed to use the actual code or the link ( should specify it) Thanks, shmezi

Sure send it

**Comment by shmezi** [comment]
@Auties00 I meant that you send a snippet.

**Comment by Auties00** [comment]
Fixed in release 3.4.0
