### ISSUE TITLE
Try to open connection and nothing happens.

### ISSUE THREAD

**Issue by PandaTwoo** [Auties00/Whatsapp4j#229]
I'm using the following code to try to establish a connection in whatsapp but nothing happens, the console doesn't show the QRCode or anything like that. Even if I try to use the QrHandler toString and print the QrCode in string, just don't appears nothing on console.

       WhatsappOptions opt = WhatsappOptions.WebOptions
                .builder()
                .autodetectListeners(true)
                .textPreviewSetting(TextPreviewSetting.ENABLED_WITH_INFERENCE)
                .historyLength(HistoryLength.THREE_MONTHS)
                .errorHandler(ErrorHandler.toTerminal())
                .qrHandler(QrHandler.toTerminal())
                .build();

        Whatsapp w = Whatsapp.lastConnection(opt);
        w.connect().join();

**Comment by lollix91** [comment]
Same problem here. i'm using 3.2.0 from Maven.

**Comment by PandaTwoo** [comment]
New code:
` WhatsappOptions opt = WhatsappOptions.WebOptions
                .builder()
                .autodetectListeners(true)
                .textPreviewSetting(TextPreviewSetting.ENABLED_WITH_INFERENCE)
                .historyLength(HistoryLength.THREE_MONTHS)
                .errorHandler(ErrorHandler.toTerminal())
                .qrHandler(QrHandler.toTerminal())
                .build();

        Whatsapp w = Whatsapp.lastConnection(opt);
        w.addNodeReceivedListener(listener -> {
            System.out.println(listener);
        });

        w.addNodeSentListener(listener -> {
            System.out.println(listener);
        });
        w.connect().join();`
        
Output:

`Node[description=iq, attributes={xmlns=md, from=s.whatsapp.net, id=40552092, type=set}, content=[Node[description=pair-device, content=[Node[description=ref, content=[50, 64, 116, 106, 80, 79, 110, 75, 116, 68, 114, 108, 115, 98, 57, 78, 100, 118, 78, 47, 97, 85, 56, 88, 89, 43, 50, 55, 120, 55, 89, 56, 53, 50, 88, 77, 115, 90, 50, 120, 108, 80, 102, 78, 78, 71, 73, 100, 122, 73, 65, 73, 47, 102, 53, 55, 66, 122, 87, 119, 72, 74, 105, 80, 111, 69, 73, 112, 70, 67, 67, 90, 57, 84, 87, 110, 85, 67, 69, 103, 61, 61]], Node[description=ref, content=[50, 64, 50, 68, 98, 51, 73, 43, 78, 43, 74, 121, 89, 119, 110, 48, 102, 55, 100, 54, 78, 105, 115, 101, 113, 50, 50, 102, 106, 114, 67, 53, 120, 105, 112, 50, 71, 122, 85, 117, 89, 105, 52, 88, 65, 90, 99, 54, 83, 104, 105, 109, 43, 82, 65, 66, 109, 97, 68, 111, 116, 56, 114, 49, 114, 122, 81, 68, 113, 120, 117, 56, 102, 113, 110, 54, 101, 52, 109, 81, 61, 61]], Node[description=ref, content=[50, 64, 71, 118, 84, 56, 72, 80, 78, 69, 88, 108, 80, 115, 85, 43, 83, 86, 70, 86, 80, 78, 80, 55, 65, 86, 53, 105, 101, 70, 49, 98, 115, 114, 65, 82, 114, 99, 114, 118, 114, 90, 98, 107, 83, 115, 107, 111, 97, 66, 119, 77, 52, 74, 71, 109, 51, 78, 111, 55, 106, 80, 107, 57, 122, 67, 119, 102, 81, 43, 108, 67, 75, 84, 105, 119, 67, 74, 117, 103, 61, 61]], Node[description=ref, content=[50, 64, 79, 118, 77, 120, 85, 115, 65, 110, 90, 56, 99, 69, 73, 112, 100, 106, 105, 107, 48, 50, 47, 69, 75, 55, 118, 80, 110, 103, 98, 53, 113, 116, 50, 97, 84, 118, 66, 71, 118, 119, 115, 80, 55, 52, 102, 85, 111, 69, 43, 76, 121, 108, 105, 104, 69, 71, 80, 86, 50, 102, 83, 57, 71, 71, 84, 90, 108, 117, 77, 89, 88, 82, 56, 108, 57, 67, 113, 103, 61, 61]], Node[description=ref, content=[50, 64, 116, 49, 69, 73, 66, 48, 111, 110, 121, 103, 98, 100, 51, 70, 106, 85, 110, 119, 88, 80, 117, 90, 82, 74, 118, 71, 116, 88, 85, 70, 67, 81, 80, 52, 86, 118, 114, 101, 56, 82, 99, 80, 97, 90, 69, 122, 79, 110, 103, 90, 74, 57, 87, 55, 43, 70, 103, 99, 66, 110, 110, 72, 86, 53, 102, 65, 67, 106, 84, 69, 68, 114, 87, 122, 82, 117, 68, 103, 61, 61]], Node[description=ref, content=[50, 64, 49, 97, 57, 49, 67, 99, 105, 89, 101, 87, 67, 116, 80, 110, 81, 74, 107, 43, 80, 99, 97, 117, 107, 48, 117, 101, 111, 99, 114, 98, 52, 52, 119, 118, 54, 86, 82, 88, 77, 49, 86, 120, 101, 73, 78, 104, 111, 82, 73, 81, 86, 72, 122, 97, 47, 102, 67, 90, 74, 43, 67, 74, 108, 83, 119, 86, 76, 84, 69, 112, 85, 79, 78, 56, 90, 73, 112, 65, 61, 61]]]]]]

[big QR code, I removed to try to keep it clean]

Node[description=iq, attributes={id=40552092, to=s.whatsapp.net, type=result}]`

If it's supposed to show only with these listeners, seems everything OK, I was just dumb. If don't, I really don't know what happened.

**Comment by Auties00** [comment]
> New code:
> `WhatsappOptions opt = WhatsappOptions.WebOptions
>                 .builder()
>                 .autodetectListeners(true)
>                 .textPreviewSetting(TextPreviewSetting.ENABLED_WITH_INFERENCE)
>                 .historyLength(HistoryLength.THREE_MONTHS)
>                 .errorHandler(ErrorHandler.toTerminal())
>                 .qrHandler(QrHandler.toTerminal())
>                 .build();
> 
>         Whatsapp w = Whatsapp.lastConnection(opt);
>         w.addNodeReceivedListener(listener -> {
>             System.out.println(listener);
>         });
> 
>         w.addNodeSentListener(listener -> {
>             System.out.println(listener);
>         });
>         w.connect().join();`
>         
> Output:
> 
> `Node[description=iq, attributes={xmlns=md, from=s.whatsapp.net, id=40552092, type=set}, content=[Node[description=pair-device, content=[Node[description=ref, content=[50, 64, 116, 106, 80, 79, 110, 75, 116, 68, 114, 108, 115, 98, 57, 78, 100, 118, 78, 47, 97, 85, 56, 88, 89, 43, 50, 55, 120, 55, 89, 56, 53, 50, 88, 77, 115, 90, 50, 120, 108, 80, 102, 78, 78, 71, 73, 100, 122, 73, 65, 73, 47, 102, 53, 55, 66, 122, 87, 119, 72, 74, 105, 80, 111, 69, 73, 112, 70, 67, 67, 90, 57, 84, 87, 110, 85, 67, 69, 103, 61, 61]], Node[description=ref, content=[50, 64, 50, 68, 98, 51, 73, 43, 78, 43, 74, 121, 89, 119, 110, 48, 102, 55, 100, 54, 78, 105, 115, 101, 113, 50, 50, 102, 106, 114, 67, 53, 120, 105, 112, 50, 71, 122, 85, 117, 89, 105, 52, 88, 65, 90, 99, 54, 83, 104, 105, 109, 43, 82, 65, 66, 109, 97, 68, 111, 116, 56, 114, 49, 114, 122, 81, 68, 113, 120, 117, 56, 102, 113, 110, 54, 101, 52, 109, 81, 61, 61]], Node[description=ref, content=[50, 64, 71, 118, 84, 56, 72, 80, 78, 69, 88, 108, 80, 115, 85, 43, 83, 86, 70, 86, 80, 78, 80, 55, 65, 86, 53, 105, 101, 70, 49, 98, 115, 114, 65, 82, 114, 99, 114, 118, 114, 90, 98, 107, 83, 115, 107, 111, 97, 66, 119, 77, 52, 74, 71, 109, 51, 78, 111, 55, 106, 80, 107, 57, 122, 67, 119, 102, 81, 43, 108, 67, 75, 84, 105, 119, 67, 74, 117, 103, 61, 61]], Node[description=ref, content=[50, 64, 79, 118, 77, 120, 85, 115, 65, 110, 90, 56, 99, 69, 73, 112, 100, 106, 105, 107, 48, 50, 47, 69, 75, 55, 118, 80, 110, 103, 98, 53, 113, 116, 50, 97, 84, 118, 66, 71, 118, 119, 115, 80, 55, 52, 102, 85, 111, 69, 43, 76, 121, 108, 105, 104, 69, 71, 80, 86, 50, 102, 83, 57, 71, 71, 84, 90, 108, 117, 77, 89, 88, 82, 56, 108, 57, 67, 113, 103, 61, 61]], Node[description=ref, content=[50, 64, 116, 49, 69, 73, 66, 48, 111, 110, 121, 103, 98, 100, 51, 70, 106, 85, 110, 119, 88, 80, 117, 90, 82, 74, 118, 71, 116, 88, 85, 70, 67, 81, 80, 52, 86, 118, 114, 101, 56, 82, 99, 80, 97, 90, 69, 122, 79, 110, 103, 90, 74, 57, 87, 55, 43, 70, 103, 99, 66, 110, 110, 72, 86, 53, 102, 65, 67, 106, 84, 69, 68, 114, 87, 122, 82, 117, 68, 103, 61, 61]], Node[description=ref, content=[50, 64, 49, 97, 57, 49, 67, 99, 105, 89, 101, 87, 67, 116, 80, 110, 81, 74, 107, 43, 80, 99, 97, 117, 107, 48, 117, 101, 111, 99, 114, 98, 52, 52, 119, 118, 54, 86, 82, 88, 77, 49, 86, 120, 101, 73, 78, 104, 111, 82, 73, 81, 86, 72, 122, 97, 47, 102, 67, 90, 74, 43, 67, 74, 108, 83, 119, 86, 76, 84, 69, 112, 85, 79, 78, 56, 90, 73, 112, 65, 61, 61]]]]]]
> 
> [big QR code, I removed to try to keep it clean]
> 
> Node[description=iq, attributes={id=40552092, to=s.whatsapp.net, type=result}]`
> 
> If it's supposed to show only with these listeners, seems everything OK, I was just dumb. If don't, I really don't know what happened.

So it doesn't show without those listeners?

**Comment by Auties00** [comment]
Should be fixed with 3.2.1, let me know

**Comment by 19Maury85** [comment]
I updated to 3.2.1, but not resolved.
I have freezed code and no qr code...
I use the same code in this issue

**Comment by Auties00** [comment]
> I updated to 3.2.1, but not resolved.
> I have freezed code and no qr code...
> I use the same code in this issue

Are you sure that you aren't already logged in?

**Comment by 19Maury85** [comment]
> 

I removed the folder, so I run from clean situation.
Delete old connection from the phone and delete the folder "whatsappweb4j"

**Comment by Auties00** [comment]
> > 
> 
> I removed the folder, so I run from clean situation. Delete old connection from the phone and delete the folder "whatsappweb4j"

I can confirm that the issue doesn't happen with the code provided in the issue

**Comment by 19Maury85** [comment]
> > I removed the folder, so I run from clean situation. Delete old connection from the phone and delete the folder "whatsappweb4j"
> 
> I can confirm that the issue doesn't happen with the code provided in the issue

There is an idea on what can be?
It’s possibile that I not receiving response?
How can I check?
I try to debug your library code and there is all fine, but I never blocked on qr generation

**Comment by Auties00** [comment]
> > > I removed the folder, so I run from clean situation. Delete old connection from the phone and delete the folder "whatsappweb4j"
> > 
> > I can confirm that the issue doesn't happen with the code provided in the issue
> 
> There is an idea on what can be?
> It’s possibile that I not receiving response?
> How can I check?
> I try to debug your library code and there is all fine, but I never blocked on qr generation

Add a node sent and received listener and send me the output

**Comment by 19Maury85** [comment]
> > > > I removed the folder, so I run from clean situation. Delete old connection from the phone and delete the folder "whatsappweb4j"
> > > 
> > > 
> > > I can confirm that the issue doesn't happen with the code provided in the issue
> > 
> > 
> > There is an idea on what can be?
> > It’s possibile that I not receiving response?
> > How can I check?
> > I try to debug your library code and there is all fine, but I never blocked on qr generation
> 
> Add a node sent and received listener and send me the output

Sorry I'm not understand. 
You mean to add listeners to send and receive messages?

**Comment by Auties00** [comment]
> > > > > I removed the folder, so I run from clean situation. Delete old connection from the phone and delete the folder "whatsappweb4j"
> > > > 
> > > > 
> > > > I can confirm that the issue doesn't happen with the code provided in the issue
> > > 
> > > 
> > > There is an idea on what can be?
> > > It’s possibile that I not receiving response?
> > > How can I check?
> > > I try to debug your library code and there is all fine, but I never blocked on qr generation
> > 
> > Add a node sent and received listener and send me the output
> 
> Sorry I'm not understand. 
> You mean to add listeners to send and receive messages?
> 

No, do something like:
```
whatsapp.addNodeReceivedListener(listener -> {
        System.out.println(listener);
    });

    whatsapp.addNodeSentListener(listener -> {
        System.out.println(listener);
    });
```

**Comment by 19Maury85** [comment]
> whatsapp.addNodeReceivedListener(listener -> {
>         System.out.println(listener);
>     });
> 
>     whatsapp.addNodeSentListener(listener -> {
>         System.out.println(listener);
>     });

Ah ok, I already did it, but nothing is printed.
I added a breakpoint to show what is the listener value, but not stop there

**Comment by FurmigaHumana** [comment]
Are you on a single threaded environment? Maybe calling .join is locking everything? I had to get lucky to be able to login but on 3.2.1 is fixed for me, events are firing properly and every time I try to login it works now.

**Comment by 19Maury85** [comment]
> Are you on a single threaded environment? Maybe calling .join is locking everything? I had to get lucky to be able to login but on 3.2.1 is fixed for me, events are firing properly and every time I try to login it works now.

Yes I'm trying from a main class for testing (I'm writing for now a main for some data elaboration and then need to send specific messages)

**Comment by 19Maury85** [comment]
I'm trying with Spring boot to, but is freezing

**Comment by Auties00** [comment]
> > Are you on a single threaded environment? Maybe calling .join is locking everything? I had to get lucky to be able to login but on 3.2.1 is fixed for me, events are firing properly and every time I try to login it works now.
> 
> Yes I'm trying from a main class for testing (I'm writing for now a main for some data elaboration and then need to send specific messages)

Can you show me your full code and send the log that i asked before!

**Comment by 19Maury85** [comment]
This with the same code in the issue:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/20571688/226325941-125eda63-e57a-4dc1-be7c-82ffc44cd818.png">

If I implement all listeners, I have blank console, but when stopping the code, I've get in console:
onSocketEvent: it.auties.whatsapp.api.Whatsapp@389914e4, CLOSE
onSocketEvent: CLOSE

the same if I try with Spring boot

**Comment by 19Maury85** [comment]
There is something that Whatsapp4J don't like....
I try with new clean project and now is working

If you want to investigate, my dependencies are:

`
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.5.12</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.13</version>
		</dependency>

		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.1.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.1.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.14.3</version>
		</dependency>

		
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client</artifactId>
			<version>1.32.2</version>
		</dependency>
		<dependency>
			<groupId>com.google.oauth-client</groupId>
			<artifactId>google-oauth-client-jetty</artifactId>
			<version>1.32.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-gmail</artifactId>
			<version>v1-rev20211108-1.32.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-sheets</artifactId>
			<version>v4-rev20221216-2.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-drive</artifactId>
			<version>v3-rev20230212-2.0.0</version>
		</dependency>

		
		<dependency>
			<groupId>com.github.auties00</groupId>
			<artifactId>whatsappweb4j</artifactId>
			<version>3.2.1</version>
		</dependency>
`

**Comment by Auties00** [comment]
I'll mark this issue as closed as it looks like it's fixed
I'll open a new one for the last  report which could be an issue of the library
